name: Hexo Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn install
      - name: Fix File Modify Date
        run: |
          git ls-files | while read filepath; do touch -d "$(git log -1 --format='@%ct' $filepath)" "$filepath" && echo "Fixed: $filepath"; done
      - name: Build Site
        run: |
          export TZ='Asia/Shanghai'
          yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public    # source部署目录
          publish_branch: deploy # 目标部署分支  
          cname: wangshuaiqiang.chat

      #- name: Setup Deploy Private Key #部署git hexo私钥到构建容器中
      #  env:
      #    HEXO_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
      #  run: |
      #    mkdir -p ~/.ssh/
      #    echo "$HEXO_DEPLOY_KEY" > ~/.ssh/id_rsa
      #    chmod 600 ~/.ssh/id_rsa
      # #获取自己服务器的主机的公钥，添加构建容器中；
      #    ssh-keyscan host.com >> ~/.ssh/known_hosts
      # - name: Deploy to VPS  # #部署到VPS，配置文件在/_config.yml；其他节点如gitee也需要添加公钥
      #  run: yarn deploy
      # #备注---其他平台添加公钥链接
      # #https://github.com/settings/ssh/new
      # #https://gitee.com/profile/sshkeys
      # #https://gitlab.com/profile/keys
      # #https://e.coding.net/

